/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        PdfSample1 s1 = new PdfSample1();
        s1.createPdf();
        PdfSample2 s2 = new PdfSample2();
        s2.updatePdf();
        PdfSample3 s3 = new PdfSample3();
        s3.createPdf();
        PdfFormSample1 sf1 = new PdfFormSample1();
        sf1.updatePdf();
        System.out.println(new App().getGreeting());
    }
}
